### ISSUE TITLE
using Genie

### ISSUE THREAD

**Issue by EricForgy** [essenciary/Genie.jl#10]
At some point, we should aim to be able to do the following:

~~~julia
julia> Pkg.clone("https://github.com/essenciary/Genie.jl.git")
julia> using Genie
~~~

Unless I'm confused, the shortest distance to be able to run Genie is:

~~~julia
julia> Pkg.clone("https://github.com/JuliaDB/PostgreSQL.jl.git")
julia> using PostgreSQL
julia> Pkg.clone("https://github.com/essenciary/Genie.jl.git")
julia> include(Pkg.dir("Genie","genie.jl"))
~~~

Also see #9

**Comment by essenciary** [comment]
Per the README

In order to start a Genie interactive session through the Julia REPL, just type:
$> julia -L genie.jl --color=yes -q

Then 
```julia
using Genie, Model
```

**Comment by essenciary** [comment]
But normally the workflow is more in the lines of a Rails app: 
1. setup a new app
2. generate your MVC files (generators already available, try `./genie -h`)
3. setup your routes 
4. (start server and ) serve

**Comment by EricForgy** [comment]
But this isn't a Rails app. I never run anything from the command line. Not even your initial one line script to launch the REPL and run genie.jl. I just click on the Julia REPL and expect to be able to get to work. That is what other Julia developers would expect too. It shouldn't be too difficult to rearrange a few things so that from a fresh REPL, you just type 

~~~julia
julia> using Genie
~~~

and it just works without the initial script.

I'd suggest keeping this open as a reminder to get around to fixing this one day even if it isn't so urgent right now, but up to you :)

If I decide to use Genie, this would be one of my first PRs so I could avoid opening up a separate command window (that I would never use for anything else except running that script) :)

Another reason to fix this is for developers using Juno or some other IDE. In this case, it should be possible to get to work without opening a command window OR the REPL.

This is a minor issue. The current situation doesn't stop anyone from playing around with Genie. I just opened the issue because I consider a "To do" item for some day.
