### ISSUE TITLE
cann't build genie

### ISSUE THREAD

**Issue by Roboid537** [essenciary/Genie.jl#103]
I'm facing the following error while building Genie.
![er](https://user-images.githubusercontent.com/34138037/50947149-e3d35680-14c2-11e9-8dea-9e3eef1bbf58.JPG)

**Comment by Roboid537** [comment]
Version 1.0.3

**Comment by essenciary** [comment]
I have no idea what to make of this - I suggest opening an issue with EzXML, that's where the error originates, sorry.

**Comment by essenciary** [comment]
I'm going to close this as it's not actionable - I suggest creating a new environment for Genie and installing the latest version and trying again.
