### ISSUE TITLE
How to hash and add salt?

### ISSUE THREAD

**Issue by xiaodaigh** [essenciary/Genie.jl#104]
I can't find any hashing algorithms like bcrypt as part of the framework. So how do I securely hash user passwords and add salt?

**Comment by xiaodaigh** [comment]
If you cna decrypt it's not secure even if you throw away the encryption key. Was looking for a one-way hash like bcrypt

**Comment by tcopestake** [comment]
https://github.com/Khrodor/Cryptic.jl

Looks like this supports bcrypt?

**Comment by essenciary** [comment]
Ah, I see - yes, you can add your own dependency to models/controllers, Genie does not provide that. The `Encryption` module is used for automatic encryption of cookie data, which needs to be reversible.
