### ISSUE TITLE
Escher interoperability

### ISSUE THREAD

**Issue by sirinath** [essenciary/Genie.jl#11]
Can you have ability to interop with http://escher-jl.org/ and re use pages writen for it.

**Comment by essenciary** [comment]
I would like to look into this at some point. I can see 2 ways to go about this. One, use Escher as the view layer, but I don't know if that's easily doable as it comes with it's own server. Depends on how straightforward it would be to decouple it from the server component. Two, which is probably the way to go, use Genie components with Escher, like for example the ORM. Once the framework will reach a stable v1, I'm planning on separating useful components into separate packages, the Model layer being the first one.

**Comment by sirinath** [comment]
Also maybe the two projects can collaborate at some point share the functionality.

**Comment by PallHaraldsson** [comment]
1. I was going to open an issue about separating SearchLight (the ORM) from, but I'm in no rush.

Just a question, it's not only that it could be useful for Escher(?), couldn't it also be useful for non-web GUIs? [I'm kind of ignorant on web-frameworks, seems ORM is they are more-or-less, independent of GUIs/web stack, but maybe not the other way around..?]

2. I'm not sure it's doable.. but could web and non-web GUI be abstracted out? Not sure if anyone does (hybrid apps are close..). [E.g. PyPlot is already independent of [non-web] GUI backend, could it be even more independent?]

3. While I'm at it, you use DBI, is that outdated (but still used for PostgreSQL), with DBAPI newer and better abstraction of databases?
