### ISSUE TITLE
local environment Required?

### ISSUE THREAD

**Issue by stefan911** [essenciary/Genie.jl#110]
Genie seems to require a local environment on both 1.1 and 1.0 julia, updating the docs would be helpful.

**Comment by essenciary** [comment]
@stefan911 I'm not sure what you mean by that

**Comment by stefan911** [comment]
Nice to see your work on Genie, I have high hopes for Julia as a general
purpose language.   I'm suggesting Pkg "] activate ."  rather than running
Genie out of the base environment until Genie, HTTP, MbedTLS become more
stable.   I ran into versioning issues that are easily solved by running
the same versions of packages your using.

**Comment by essenciary** [comment]
I see, thanks for the details. Sure, that's an important best practice and Genie implements it: all the Genie _apps_ are created with their own environment. It certainly wouldn't hurt to indicate this best practice in the README but: 
a. it's not a requirement
b. in some cases the users might actually need it in their global environment
c. the above applies to all packages in general
