### ISSUE TITLE
Genie not processing image uploaded through HTML form.

### ISSUE THREAD

**Issue by bellascalzi1** [essenciary/Genie.jl#111]
Hi guys, having a slight problem with using Genie, and I was hoping someone could help. 

So I am trying to create a website using Genie that takes in an image from the user using a HTML form, processes it using Julia (I am thresholding the image, although that is not relevant) and then display the processed image to the user. However, I am having trouble getting the image from the HTML form into my julia function that processes the image. (I am using ```@params```). I can get text elements from the form just fine, as is shown in the ```readme.md``` tutorial. but I cannot get the image for some reason. As soon as I submit the form, this is the error that I get:

![image](https://user-images.githubusercontent.com/16617321/52605768-0c82ad80-2ec0-11e9-86fd-5c395e865e8b.png)

This is the form that I am using to grab the image:

```html
<form action="$(Genie.Router.link_to(:threshold_img))" method="POST" enctype="multipart/form-data">

  <input type="radio" name="algorithm" value="otsu" checked/>Otsu<br/>
  <input type="radio" name="algorithm" value="unimodal" checked/>Unimodal<br/>
  <input type="radio" name="algorithm" value="minimum" checked/>Minimum<br/>

	<p><input type="file"  accept="image/*" name="image" id="file"></p>


  <input type="submit" value="Threshold Image" />
</form>
```
How I am using ```@params``` to grab the image from the form (Julia code that is also supposed to process the image

```julia
function threshold()

  # What thresholding algorithm the user has chosen. WORKS
  algorithm = @params(:algorithm)

  # The image that the user has uploaded. ERROR IS HERE
  img = @params(:image)

  html!(:books, :threshold, res = result, alg=algorithm)
end
```
Route to the form:
```julia
route("/upload_img", BooksController.upload_img)
```
Route to the julia function that is supposed to process the image:
```julia
route("/threshold", BooksController.threshold, method = POST, named = :threshold_img)
```

**What I have tried:**
Have tried adding the parameter in the html!() function instead of just in the function eg:

``` html!(:books, :threshold, res = result, alg=algorithm, image = @params(:image))```

Packages:
```
  [c43c736e] Genie v0.1.0 #master (https://github.com/essenciary/Genie.jl)
  [cd3eb016] HTTP v0.8.0
  [682c06a0] JSON v0.20.0
  [39ec1447] Millboard v0.2.0
  [4d1e1d77] Nullables v0.0.8
  [5fb14364] OhMyREPL v0.5.0
  [295af30f] Revise v1.0.2
  [0aa819cd] SQLite v0.7.0
  [340e8cb6] SearchLight v0.1.0 #master (https://github.com/essenciary/SearchLight.jl)
  [ddb6d928] YAML v0.3.2
```
Julia:1.0.2
OS: Windows

Thank you in advance to anyone who can help, I have almost zero web dev experience and I understand my issue might be a little convoluted!!

**Comment by EricForgy** [comment]
I'm taking a wild guess, but I notice you have HTTP v0.8.0. There are quite a lot of changes from HTTP v0.7.1 to v0.8.0 and I'm not sure @essenciary has had a chance to test Genie on HTTP v0.8.0 yet 🤔 

I'm not sure how to do it, but you might try pinning HTTP to v0.7.1 and see if that helps.

```julia
julia>?Pkg.pin
```

points to `Packagespec`, but I think that is supposed to be

```julia
julia>?Pkg.Types.PackageSpec
```

but I've never used that 😅

**Comment by essenciary** [comment]
@bellascalzi1 Thanks for the detailed issue report. 
Support for file uploads got dropped during the HTTP migration/update. I've added back the functionality. 

You can access `@params(:FILES)` where you have a `Vector{Pair{String,HttpFile}}` - the `String` is the name of the input in the form and the `HttpFile` represents the uploaded file. It has 3 fields: `name`, `mime` and `data`.

Ex: 
```
using Pkg
pkg"activate ."

using Genie, Genie.Router, Genie.Renderer

form = """
<form action="/" method="POST" enctype="multipart/form-data">
  <input type="text" name="greeting" value="hello genie" /><br/>
  <input type="file" name="fileupload" /><br/>
  <input type="submit" value="Submit" />
</form>
"""

route("/") do
  html!(form)
end

route("/", method = POST) do
  for (name,file) in @params(:FILES)
    write(file.name, IOBuffer(file.data))
  end

  @show @params(:greeting)

  @params(:greeting)
end

Genie.AppServer.startup(async = false)
```

Obviously, don't forget to update to latest Genie for this to work! 

I'm thinking about adding a higher level API to manage uploads (like saving to a temp file, saving to an uploads dir, etc). What do you think?

**Comment by essenciary** [comment]
Of course, the payload can also be accessed by label / input name: 
```julia
write(@params(:FILES)["fileupload"].name, IOBuffer(@params(:FILES)["fileupload"].data))
```
