### ISSUE TITLE
CSS and JS not found

### ISSUE THREAD

**Issue by del2z** [essenciary/Genie.jl#112]
I follow the tutorial to start a new app. I want some style in html page. But uncommenting the "stylesheets" and "javascript" line in app/layouts/app.jl.html is not working. Error message from Chrome says
GET http://localhost:8000/css/application.css net::ERR_ABORTED 404 (Not Found)
GET http://localhost:8000/js/application.js net::ERR_ABORTED 404 (Not Found)
I try different path for "href", none of them works as expected.

**Comment by del2z** [comment]
OS Env:
MacOS Mojave
Julia 1.0.3
Genie 0.1.0 #master

**Comment by essenciary** [comment]
@del2z That's a bit more complicated. Genie is designed to use a frontend stack based on Yarn and Webpack - I can provide instructions for that. 
I'll take a look to see if I can distribute some default built css and js file with a new app. 
Of course, you can also include your own by placing them in the `public` folder.

**Comment by del2z** [comment]
Thanks, css and js files in `public` work fine.
