### ISSUE TITLE
Genie.AppServer.startup() not working (ERR_CONNECTION_REFUSED)

### ISSUE THREAD

**Issue by pbouffard** [essenciary/Genie.jl#113]
For some reason `Genie.AppServer.startup()` doesn't work for me -- I get an `ERR_CONNECTION_REFUSED` in my browser. Yet when I run `./server` in the `your_cool_new_app/bin` folder it does work. To be clear this is what I'm doing:

```
using Genie
import Genie.Router: route
route("/") do
  "Hi there!"
end
Genie.AppServer.startup()
```

In case it's relevant, from the REPL (or if I do the same by putting the above in a script). The output at the terminal is:

```
$ julia -i ./test.jl 
[ Info: Recompiling stale cache file /Users/patrick/.julia/compiled/v1.1/Genie/8eazC.ji for Genie [c43c736e-a2d1-11e8-161f-af95117fbd1e]
2019-02-13 13:04:34:DEBUG:Main:Web Server starting at 127.0.0.1:8000
2019-02-13 13:04:36:DEBUG:Main:Web Server running at 127.0.0.1:8000
```

.. but running `server`:

```
$ bin/server
 _____         _
|   __|___ ___|_|___
|  |  | -_|   | | -_|
|_____|___|_|_|_|___|


Starting Genie in >> DEV << mode 

[ Info: Recompiling stale cache file /Users/patrick/.julia/compiled/v1.1/Genie/8eazC.ji for Genie [c43c736e-a2d1-11e8-161f-af95117fbd1e]
2019-02-13 13:03:10:DEBUG:Main:Web Server starting at 0.0.0.0:8000
```

Note that I don't think it's some kind of firewalling because I can get `python -m http.server` to work just fine.

Julia 1.1.0, MacOS Mojave.

**Comment by pbouffard** [comment]
.. after some more twiddling this might just be a documentation thing. On the landing page I think there's a missing step to get the `> genie` prompt. I think in Step 3 you probably should have something like:

```
$ cd your_cool_new_app
$ bin/repl
julia> Genie.AppServer.startup()
Listening on 0.0.0.0:8000...

# Visit http://localhost:8000/hello in your favorite browser
```

(note a couple other minor differences; at least for me the prompt is `julia>` not `>genie`, and `Genie.` is needed at the front of the `startup()` command.)

As it's written now it's easy to think that after installation and creating `your_cool_new_app` that it's possible to just start a Julia REPL, and do 

```
route("/hello") do
  "Hello - Welcome to Genie!"
end
Genie.AppServer.startup()
```

**Comment by tweenietomatoes** [comment]
Did you try for 127.0.0.1 ?

**Comment by pbouffard** [comment]
@tweenietomatoes Yes, I tried that, localhost, and 0.0.0.0. See my followup comment though.

**Comment by tweenietomatoes** [comment]
It might be like firewall blockage too (i am not familiar with macos), Are u using initial release or master? I strongly recommend master which Adrian updated http.jl to 0.8.

**Comment by bellascalzi1** [comment]
Am having exactly the same issue as well. I can also get a Python http.server running but cannot seem to get Genie working. I am using master and have got HTTP at 0.8.

**Comment by betttris13** [comment]
Having been working with bellascalzi1 the problem seems to have started occurring sometime yesterday morning. The server was working fine before that.

**Comment by bellascalzi1** [comment]
Found a short-term fix for people on Windows:
Change what is in ```bin/server.bat``` to be:
```C:\Users\YOUR_NAME_HERE\AppData\Local\Julia-1.0.2\bin\julia -L ../genie.jl --color=yes --depwarn=no -q -- bootstrap.jl s %*```

**Comment by essenciary** [comment]
@bellascalzi1 @betttris13 I pushed some major changes yesterday.
There seem to be multiple issues here, for many, I need to update the README (like no more `genie>` prompt, it was just a cosmetic change that complicated matters and added extra dependencies). 

So, to conclude: 
+ starting from REPL via Genie.AppServer.startup() drops connections
+ starting from ./bin/server works

Is that correct?

**Comment by essenciary** [comment]
OK, I'm trying various cases: 

1. on the fly app:

```julia
(v1.1) pkg> activate .

julia> using Genie
[ Info: Recompiling stale cache file /Users/adrian/.julia/compiled/v1.1/Genie/8eazC.ji for Genie [c43c736e-a2d1-11e8-161f-af95117fbd1e]

julia> using Genie.Router

julia> route("/") do
       "hello"
       end
Genie.Router.Route("GET", "/", getfield(Main, Symbol("##3#4"))(), Dict{Symbol,Any}(), Function[], Function[])

julia> Genie.AppServer.startup()
2019-02-14 08:33:38:DEBUG:Main:Web Server starting at 127.0.0.1:8000
2019-02-14 08:33:38:DEBUG:Main:Web Server running at 127.0.0.1:8000

julia> 2019-02-14 08:33:53:DEBUG:Main:[2019-02-14T08:33:53.091] -- :/ -- Done
```

All good!

**Comment by essenciary** [comment]
2. new app, auto started

```julia
(v1.1) pkg> activate .

julia> using Genie

julia> Genie.newapp("ServerTest")
2019-02-14 08:35:34:INFO:Main:Done! New app created at /Users/adrian/Dropbox/Projects/genie-tests/ServerTest
2019-02-14 08:35:34:DEBUG:Main:Changing active directory to ServerTest
2019-02-14 08:35:34:DEBUG:Main:Installing app dependencies
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
2019-02-14 08:35:41:INFO:Main:Starting your brand new Genie app - hang tight!
 _____         _
|   __|___ ___|_|___
|  |  | -_|   | | -_|
|_____|___|_|_|_|___|


Starting Genie in >> DEV << mode

2019-02-14 08:35:48:DEBUG:Main:Web Server starting at 127.0.0.1:8000
2019-02-14 08:35:48:DEBUG:Main:Web Server running at 127.0.0.1:8000

julia> 2019-02-14 08:36:00:DEBUG:Main:[2019-02-14T08:36:00.646] -- :/ -- Done


┌ Warning: throttling 127.0.0.1
└ @ HTTP.Servers ~/.julia/packages/HTTP/GN0Te/src/Servers.jl:54
┌ Warning: throttling 127.0.0.1
└ @ HTTP.Servers ~/.julia/packages/HTTP/GN0Te/src/Servers.jl:54
2019-02-14 08:36:05:DEBUG:Main:[2019-02-14T08:36:05.506] -- :/ -- Done


┌ Warning: throttling 127.0.0.1
└ @ HTTP.Servers ~/.julia/packages/HTTP/GN0Te/src/Servers.jl:54
2019-02-14 08:36:45:DEBUG:Main:[2019-02-14T08:36:45.036] -- :/hi -- Done


┌ Warning: throttling 127.0.0.1
└ @ HTTP.Servers ~/.julia/packages/HTTP/GN0Te/src/Servers.jl:54
2019-02-14 08:36:49:DEBUG:Main:[2019-02-14T08:36:49.377] -- :/hello -- Done


2019-02-14 08:36:50:DEBUG:Main:[2019-02-14T08:36:50.145] -- :/hello -- Done
```

All good!

**Comment by essenciary** [comment]
3. `bin/server` in existing app: 

```julia
 ~/P/genie-tests  cd ServerTest/                                                                                                Thu Feb 14 08:38:08 2019
 ~/P/g/ServerTest  bin/server                                                                                                   Thu Feb 14 08:38:11 2019
 _____         _
|   __|___ ___|_|___
|  |  | -_|   | | -_|
|_____|___|_|_|_|___|


Starting Genie in >> DEV << mode

[ Info: Recompiling stale cache file /Users/adrian/.julia/compiled/v1.1/Genie/8eazC.ji for Genie [c43c736e-a2d1-11e8-161f-af95117fbd1e]
2019-02-14 08:38:34:DEBUG:Main:Web Server starting at 0.0.0.0:8000
2019-02-14 08:38:51:DEBUG:Main:[2019-02-14T08:38:51.012] -- :/hello -- Done


2019-02-14 08:39:05:DEBUG:Main:[2019-02-14T08:39:05.037] -- :/hello -- Done
```

All good!

**Comment by essenciary** [comment]
4. `bin/repl` in existing app: 

```julia
 !  ~/P/g/ServerTest  bin/repl                                                                                          1.8m  Thu Feb 14 08:40:04 2019
 _____         _
|   __|___ ___|_|___
|  |  | -_|   | | -_|
|_____|___|_|_|_|___|


Starting Genie in >> DEV << mode

julia> Genie.AppServer.startup()
2019-02-14 08:40:29:DEBUG:Main:Web Server starting at 127.0.0.1:8000
2019-02-14 08:40:29:DEBUG:Main:Web Server running at 127.0.0.1:8000

julia> 2019-02-14 08:40:40:DEBUG:Main:[2019-02-14T08:40:40.578] -- :/hello -- Done


2019-02-14 08:40:42:DEBUG:Main:[2019-02-14T08:40:42.06] -- :/hello -- Done
```

All good!

**Comment by essenciary** [comment]
I tried everything, I can't reproduce it. 

The thing is, yesterday I pushed some major architectural change: now all Genie apps are wrapped in dedicated modules. So "MyApp" is now running in a dedicated `MyApp` module, which is awesome for many reasons (encapsulation, performance, etc). 

So the architecture of the Genie apps has changed - although, as far as I can tell, old apps still work. Can you please help me clarify: 
1 - are you on the latest `Genie#master`? If not, please update. Please also beware that you might have to update the `Genie` _within_ the app. So open a Julia REPL in the app's folder and `pkg> activate .` and `pkg> up`.
2 - is the problem related to new apps or existing apps?
3 - what exactly doesn't work - please provide steps on how to reproduce
4 - the output of `julia> versioninfo()`
5 - the output of `pkg> st` within the Genie app. 

Sorry for the problems guys and thanks for your help! I'm pretty sure that this was the last major change and a pretty valuable one. Once this is cleared up I'll tag Genie version 1.0 so there will be API stability.

**Comment by essenciary** [comment]
One thing I can see is that `bin/server` starts the server on `0.0.0.0` (which is all interfaces) while `AppServer.startup` starts in on `127.0.0.1` which is `localhost`. I'll look into this now, makes sense to be consistent and start on the same interface all the time.

**Comment by bellascalzi1** [comment]
Updated to the latest Genie, and just tried to open up my app today. The web server starts correctly now using ```Genie.AppServer.startup()```! I'm not quite sure what happened, i'm sorry for all the trouble! 😄

**Comment by essenciary** [comment]
@bellascalzi1 Yeee! Awesome, thanks for letting me know.
