### ISSUE TITLE
Feature: Clearer exceptions and error messages

### ISSUE THREAD

**Issue by Helveg** [essenciary/Genie.jl#118]
I'm working with Genie now for a few days and I've noted that:
* The exceptions are "packed" inside of a Distributed.RemoteException and the original error is partly obfuscated.
* The stacktrace is the abstract bootstrapping up until AppServer.jl:71 but not the relevant part inside the code.

It would be nice if the Distributed.RemoteException would be unpacked and the containing error reinstated, formatted and the stacktrace could be cleaned up to show the relevant parts of the user-written code.

**Comment by essenciary** [comment]
Yes, I agree - the exceptions need a bit of ♥️

**Comment by essenciary** [comment]
@Helveg I cleaned up the exceptions a bit. Nothing major but the exception stack now starts at the actual application error, instead of being deep in the server exception. Much more readable.

**Comment by essenciary** [comment]
I think this is good enough, for now
