### ISSUE TITLE
"using Genie" creates a directory?

### ISSUE THREAD

**Issue by EricForgy** [essenciary/Genie.jl#122]
Hi @essenciary ,

I wanted to give Genie a spin and got the following:

```julia
julia> using Genie
[ Info: Precompiling Genie [c43c736e-a2d1-11e8-161f-af95117fbd1e]
ERROR: LoadError: LoadError: SystemError (with log): mkdir: Permission denied
```

I've received this feedback myself, so I'll pass it on. I don't think a package should start any servers or make any changes to the file system when all you do is

```julia
julia> using Genie
```

Similar to 

```julia
julia> Genie.AppServer.startup()
```

maybe there should be a

```julia
julia> Genie.Logger.startup(logdir)
```

I'm glad I got that error because I would be surprised (possibly unhappy) to find Genie was manipulating my file system when all I did was `using Genie` 😅 

It also makes me nervous that I need to run as admin for a package I am not familiar with. Just some feedback. Hope all is well 😊

**Comment by essenciary** [comment]
@EricForgy It's very difficult to find the right spot when to do these things. 

Genie needs a `log` folder and a `build` folder. These are very useful for the user cause they provide logging to file and fast views rendering. After `using Genie` the logging functionality becomes available so you can `log("foo")` to file. 

There are some settings in `Configuration` - I could disable logging to file and building by default.

**Comment by EricForgy** [comment]
I'm working on it. Will submit a PR soon and we can figure it out 😊🙏
