### ISSUE TITLE
The documentation is outdated

### ISSUE THREAD

**Issue by mrkaspa** [essenciary/Genie.jl#124]
I tried to follow the guide but could not create the model and migration with the resource, and there is no a point on the guide about how to do this, I want to use only SearchLight for a project but there is no documentation for that project either

**Comment by essenciary** [comment]
@mrkaspa Which documentation are you referring to please?

**Comment by essenciary** [comment]
If you meant the documentation at Read the docs, that was indeed dated. I have removed it. For now please use Genie's README.
