### ISSUE TITLE
Question about type 

### ISSUE THREAD

**Issue by pnavaro** [essenciary/Genie.jl#126]
In this function from the tutorial, i note you set the type with a symbol :string
What are the other types available, i try :bool but it does not work.
I am not fluent with database so sorry if it is a silly question.
```julia
function up()
  create_table(:books) do
    [
      primary_key()
      column(:title, :string)
      column(:author, :string)
    ]
  end
end
```

**Comment by pnavaro** [comment]
I found an answer in the source file https://github.com/essenciary/SearchLight.jl/blob/master/src/database_adapters/SQLiteDatabaseAdapter.jl

**Comment by pnavaro** [comment]
Sorry it is a mistake it works now

**Comment by essenciary** [comment]
@pnavaro Sorry, missed this. Yes, it's a way to map Julia-like types to native DB types so that the migrations can work with multiple dbs (instead of writing db specific code).
