### ISSUE TITLE
Launch Genie app on boot 

### ISSUE THREAD

**Issue by pnavaro** [essenciary/Genie.jl#127]
Dear Genie developers,
I made a website to process data with Genie and i am very happy. Do you have an advice to launch the website on boot ?

Thanks for sharing Genie.jl

**Comment by essenciary** [comment]
@pnavaro Would you like to automatically start the app when the server reboots? On Linux?

**Comment by pnavaro** [comment]
Yes i try crontab with @reboot but it does not work.

**Comment by essenciary** [comment]
There are probably other ways but my favorite approach is using `supervisor.d` http://supervisord.org/introduction.html
It runs as a service and not only starts the app on reboot, but also if the app crashes, it gets restarted. 

---

Also, if you expect considerable traffic, use Nginx as a web server. Julia/HTTP.jl is not very good at handling static files (images, css, js, etc). If you have a lot of traffic and a lot of static files, you'll get much better performance by setting up Nginx as a reverse proxy and file cache. This has the added benefit that you'll have Nginx running on port 80 and the Genie app on a port which doesn't require root privileges. Genie can be configured to _not_ serve static assets. Also, there are settings which make the app perform better in production (no code reloads, etc). 

This won't change the fact that you need to set up `supervisor.d` to manage the Genie app. Nginx is just running on port 80 and forwarding requests to the Genie app. 

If you don't have a lot of traffic and/or the app is not accessible on the Internet, you can skip this step. 

---

I'm working on a Docker image that will be set up for running production level Genie apps. This will simplify deployments. Also, I'm writing a new section in the README for how to setup Genie to run in production. I'll hope I'll finish these soon.

**Comment by pnavaro** [comment]
I already use nginx. Supervisor is an excellent choice, i used it for bokeh applications. Thank you.

**Comment by essenciary** [comment]
You're welcome
