### ISSUE TITLE
form problem

### ISSUE THREAD

**Issue by dimitraVrs** [essenciary/Genie.jl#128]
Hello!
I am trying to create an app with a form (for adding books in a database), like the one in READEME (I followed thesteps of it). The problem is that after I write the book's values in the form and submit them, I get an error and there is no saving in the database or redirecting.
Can you help me with this problem?
Thank you in advance
P.S. I checked code twice, and it seems that there no missing parts.

**Comment by essenciary** [comment]
What is the error, please? 
Also, can you please share the output from `julia> versioninfo()` and `pkg> st`

**Comment by dimitraVrs** [comment]
500 Internal Server Error and

julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)

(v1.0) pkg> st
    Status `~/.julia/environments/v1.0/Project.toml`
  [c43c736e] Genie v0.1.0 #master (https://github.com/essenciary/Genie.jl)
  [7073ff75] IJulia v1.14.1

**Comment by essenciary** [comment]
@dimitraVrs Thanks - I'm going to need the actual error please. For example from the Terminal or on the 500 page, there's an error details button with a full stack dump.

**Comment by dimitraVrs** [comment]
It that the right one?
[error.pdf](https://github.com/essenciary/Genie.jl/files/3063279/error.pdf)

**Comment by essenciary** [comment]
Yes - looks like a problem in your code, the `save` invocation fails. Show me what's in `BooksController` please.

**Comment by dimitraVrs** [comment]
module BooksController
# Build something great

using Genie.Renderer
using Genie.Router
using Books
import SearchLight.SearchLight:find_df

function new()
  html!(:books, :new)
end

function create()
	saved=0
	df=find_df(Book)
	for i=1:size(df,1)
		if cmp(df[i,3],@params(:book_title))==0
			saved=1
			println("The book is already saved. Try saving another one!")
			redirect_t(:get_bgbooks)
		end
	end
				
	if saved==0
    		Book(title = @params(:book_title), author = @params(:book_author),genre1 = @params(:book_genre1),genre2=@params(:book_genre2),genre3 = @params(:book_genre3)) |> save && redirect_to(:get_bgbooks_new)

	end
end


end

**Comment by dimitraVrs** [comment]
My database array has five values for each book: title, author, genre1,genre2 and genre3.
Also, in function create I am trying to check if the book a user submits, is already saved. For this, use the titles and fuction cmp.

**Comment by essenciary** [comment]
@dimitraVrs `save` is from `SearchLight` so you need `using SearchLight`.
