### ISSUE TITLE
POST data

### ISSUE THREAD

**Issue by tcopestake** [essenciary/Genie.jl#13]
'lo.

I'd be interested in adding support for POST data if you don't already have it covered.

I already have some code written for getting POST and file data from my CGI module (see https://github.com/Jaylle/CGI.jl/blob/master/CGI.jl#L365 for example) - so I'd most likely use/modify that.

As for the interface, is there any preference for how this should be accessible and how it should work internally? For example, I see that GET query params are currently passed automatically as a method argument, but I like the idea of the framework not having to parse the POST/file data until an attempt is made to access said data (just to avoid doing unnecessary work). This would require having a new method (e.g. Genie.input) or module (e.g. Input.post) return an object containing the POST and/or file data on-demand, unless you could suggest an alternative.

Let me know your thoughts.

**Comment by essenciary** [comment]
@tcopestake Thanks, that would be awesome 👍 

Support for POST was the very next on my list (days away). I'm currently adding user authentication and POST is obviously a requirement. If you could contribute it, that would be excellent! Also, if you have already implemented file data support in your codebase and can easily port it over, that would be super. 

I like the idea of Input.post / Input.get / Input.files / etc. Right now the GET params are passed into a `params` dict that's passed into the controller methods. If you can provide Input.post and Input.files I'm happy to unify the APIs by adding Input.get and maybe drop `params` completely. 

Lazy processing the input can't hurt, although I can't see too many cases where we'd want to ignore what's being sent over the wire (maybe in the case of a DoS attack)?

**Comment by EricForgy** [comment]
I submitted a PR to URIParsers.jl ( https://github.com/JuliaWeb/URIParser.jl/pull/32 ) to allow easy processing of POST requests. I use this together with Pages.jl. We can all compare notes :)

**Comment by essenciary** [comment]
🎅 👍

**Comment by essenciary** [comment]
@tcopestake 
I've been successfully using Input.post in Genie for a while now - happy to say it works great!

However, I've stumbled into an issue: when POST-ing data, the spaces in the submitted data are replaced by "+". I can easily convert the "+" to " " in my POST processing function, but then the trouble is, it will also replace plus symbols inserted by the user. 

It would be awesome if the library would be extended to output the user input as exactly submitted (preserving spaces and plus symbols).
