### ISSUE TITLE
CMS

### ISSUE THREAD

**Issue by datnamer** [essenciary/Genie.jl#16]
Any plans for a CMS?

Or would it be possible to integrate with a html CMS myself?

**Comment by essenciary** [comment]
Kind of - it's still in early development phases and I'm just basically building it from the outside in, picking a project / product and building it, adding the necessary libraries in the process. 
The demo project for the current v0.6 is a blogging platform - will use Julia's Markdown for editing articles. Should not be too hard to grow into a full size CMS.

**Comment by datnamer** [comment]
I don't know HTML, CSS or JS...but if you can figure out a way to use Escher, I'd be happy to help with integration and development of the blog app.
