### ISSUE TITLE
Hydration / dehydration?

### ISSUE THREAD

**Issue by foucist** [essenciary/Genie.jl#19]
Just a dumb question, but is this the same thing as serializing & deserializing?  Because it seems like a poor name if so.

**Comment by essenciary** [comment]
In a way. It's persistence to DB and reading from DB plus the corresponding hooks. Any suggestions on how to name it better?

**Comment by jonathanBieler** [comment]
I also had some issues understanding what these names are about, reading this it seems to be a common problem.

https://stackoverflow.com/a/4929478

Maybe `fill` and `empty` (with ! ?) would be more Julian.
