### ISSUE TITLE
No YAML package for Genie-0.7.0 with Julia-0.5.0

### ISSUE THREAD

**Issue by konstantinmamontov** [essenciary/Genie.jl#21]
Hi, i tried to use Genie with Julia-0.5.0 on Windows8

Genie.jl-0.7.0>julia -L genie.jl --color=yes -q

Starting Genie in >> DEV << mode using 1 worker(s)

ERROR: LoadError: LoadError: LoadError: LoadError: ArgumentError: Module YAML no
t found in current path.
Run `Pkg.add("YAML")` to install the YAML package.

julia> Pkg.add("YAML")
ERROR: unknown package https://github.com/JuliaDB/DBI.jl required by Genie.jl-0.
7.0

Thanks in advance!

**Comment by essenciary** [comment]
Hi, sorry - just seen this 😱

Probably too late now, but you can try the latest version, it's made good progress in terms of package setup, requirements, etc. If you have time, give it a try and let me know how it goes. 
http://genieframework.com/
