### ISSUE TITLE
Extending the ORM to neo4j

### ISSUE THREAD

**Issue by datnamer** [essenciary/Genie.jl#22]
How much work would that be?

It has a different querying language and is not a relational dn, but a graph db.

Edit: Maybe I don't need a graph db? I have entities that are related to multiple categories and to each other. 

Can this be modelled currently or since tbe relationships will be many to many and there is no multiple inheritance , i would need to add code?

Maybe model composition instead of inheritance to handle the categories?

**Comment by essenciary** [comment]
My experience with graph DBs is very limited so I can't say with any degree of certainty. 

For a RDBMS the implementation should be pretty straightforward. SearchLight uses something like the bridge pattern in a structure similar to: 
[1. SearchLight Developer API] > [2. DB specific SearchLight adapter] > [3. low level Julia DB library]
1 - exposes the querying API to the developer - normally it shouldn't be touched
3 - would be the neo4j Julia library
2 - would be the adapter between 1 and 3

The corresponding files for the current PostgreSQL implementation are: 
1 - Genie.jl/lib/SearchLight/src/SearchLight.jl
2 - Genie.jl/lib/SearchLight/src/database_adapters/PostgreSQLDatabaseAdapter.jl
3 - https://github.com/JuliaDB/PostgreSQL.jl

I guess the only question is how easy would be to query the graph DB in a RDBMS manner - and by looking at the Ruby / Rails implementation, seems doable: 
https://github.com/neo4jrb/neo4j

If you go down this path let me know, happy to help - I'm curious about it.

**Comment by berzley** [comment]
@datnamer Did you ever venture down this path or possibly with another graph DB?

**Comment by datnamer** [comment]
@berzley  nope. Ended up not needing to do so.
