### ISSUE TITLE
[RFI] License

### ISSUE THREAD

**Issue by o314** [essenciary/Genie.jl#23]
Under which license is Genie.jl distributed ?

I haven't found any precise information for now.

Thanks
Oli

**Comment by essenciary** [comment]
Oli, as this is still work in progress i haven't thought much about it. I'm thinking similar to Julia should be fine, so MIT. I'll add the license file.

**Comment by o314** [comment]
Hi.
It's not so much a problem it's a work in progress - not so many 1.0 package on the linux distro side.
However for my part, the license is crucial to know if i will use / collaborate with a project.

MIT license is good to foster collaboration. GPL kills even the smallest effort of test refactoring and seems dead today https://www.theregister.co.uk/2013/04/18/github_licensing_study/

Julia need a framework. I think something like ruby on rails, symfony, zend framework or slim framework. 
Under this terms, may be i will try to come back hacking my part.

**Comment by essenciary** [comment]
Now licensed as MIT :)
