### ISSUE TITLE
Switch to HTTP.Server

### ISSUE THREAD

**Issue by quinnj** [essenciary/Genie.jl#25]
Hey @essenciary, really enjoyed your JuliaCon talk. Over the last little while, I've been working on overhauling some of the fundamental webstack packages, including HttpCommon, HttpParser, HttpServer, URIParser, and Requests.jl. I've consolidated the packages (for now) into a single [HTTP.jl](https://github.com/JuliaWeb/HTTP.jl) package that is meant to be a full replacement for the previous packages I mentioned. Functionality & APIs should be largely the same, so it shouldn't be too hard to switch over.

The long-term plan is to deprecate some of those webstack packages as they are not actively maintained.

I'll try to find some time to dig more into the Genie framework and maybe submit a PR or two to help switch over! Great stuff!

**Comment by essenciary** [comment]
@quinnj That's excellent news, thanks so much for your effort! Yeah, absolutely, I'll do the switch, thanks for the heads up! 

Any PRs are greatly appreciated! :) 

---

PS - looking forward to the updates in handling NULLs, I really liked the direction it's going, great talk! 

I personally find the handling of NULLs a bit clumsy - having to check for them and manually unwrap them really breaks the flow of the code. 

In Genie, in some places, I ended up with a helper function that checks for NULLs and returns either the unpacked value or a default value if NULL. 

As an alternative approach, did you look at Ruby's `safe navigation operator (&.)`
http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/

**Comment by essenciary** [comment]
Working on the HTTP.jl stack now
