### ISSUE TITLE
EscapeString.jl

### ISSUE THREAD

**Issue by JockLawrie** [essenciary/Genie.jl#3]
...yet another FYI:

[EscapeString](https://github.com/JockLawrie/EscapeString.jl) may or may not be helpful. AccessControl.jl uses it to escape HTML in order to prevent XSS attacks. The package is tiny at this stage, but provides a simple unified interface for escaping strings, handy for web app security. The plan is to build it out as required.

**Comment by essenciary** [comment]
@JockLawrie Ah, that's nice! I'll check it out, cheers!
