### ISSUE TITLE
Authentication layer example

### ISSUE THREAD

**Issue by GearsAD** [essenciary/Genie.jl#31]
Hi,

I'd like to use OAuth 2.0-type authentication as part of an API. I can't seem to find an example of how to implement this using the existing auth layer. Is there an example, if not could I help write one?

Thanks! Great library by the way.

**Comment by essenciary** [comment]
Genie doesn't have built in support for OAuth authentication - it offers only basic user / pass local authentication backed by DB storage. 

An OAuth 2 workflow takes place mostly on the side of the authenticating service and that dictates the implementation. In general, you only need to setup the callback URLs and the corresponding code to process the payload (authorization code and access token). 

Once you have the access token you put it on the session - or if you want to provide persistent sessions, on the cookie. If you use Genie's Cookie API, the value will be automatically encrypted before being stored on the cookie. 

What OAuth provider will you use? Here's an example provided by DigitalOcean: https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2

If you make progress with this it would be nice to refactor this into the `Genie.Authentication` module - maybe via a config option or some sort of factory `authentication(p::Provider)`.

**Comment by GearsAD** [comment]
Thanks. We're looking at using AWS Cognito with its federated logins. Still reading up on all of it, if we get it running smoothly we'll definitely try to get a PR in.

**Comment by xgdgsc** [comment]
Is ther more doc on auth? Trying to auth with ldap (call python ldap3) here.

**Comment by essenciary** [comment]
@xgdgsc We have this which works great but only supports DB backed auth: https://github.com/GenieFramework/GenieAuthentication.jl

Would be nice to add adapters support to it.
