### ISSUE TITLE
Updated signatures for route.jl

### ISSUE THREAD

**Issue by GearsAD** [essenciary/Genie.jl#32]
Hi,

We just pulled latest master branch and we see that the route definitions have changes (can't use a route(string,string...) route after recent commits. We compared the versions and those signatures have been removed. https://github.com/essenciary/Genie.jl/compare/c0cd59b...f92789e

Looking for best way forward - is there another pattern that we should follow for route definitions? The example seem to still use the old definitions - https://github.com/essenciary/genie-todo-mvc/blob/master/config/routes.jl.

Thanks!

@dehann

**Comment by essenciary** [comment]
@GearsAD Indeed I've recently updated the code to simplify routing. Now `route` only accepts `(String, Function)` or `(Function, String)`. They support two usage patterns: 
```julia
route("/uri/pattern", Controller.function) # routing to controller
route("/uri/pattern") do    # inline routing
  # logic here
end
```

These methods are here to stay. I believe that this approach is much more Julian, as both `first-class functions` and `do blocks` are idiomatic Julia. The removed methods were doing the same, but with unnecessary complexity and less performance. 

This is part of a recent overhaul of the framework which has seen many parts simplified and/or consolidated. I'm sorry that I didn't have the time to update the examples and the README yet. 

Spoiler alert, a few other important things are different in the latest commits, breaking the examples. Most notably, the way models and controllers are loaded and named has changed. Again, this was done to use Julia's best practices (`using` vs `include`), simplify and speed up various sections. 

I will update the examples and the README in the next few days/weeks.

**Comment by essenciary** [comment]
Can you provide more details, please? What is the route and what is the error that you're getting?

**Comment by GearsAD** [comment]
Sure, using the boilerplate applications generated by last year, if I don't explictly include the controllers in the routes file, it doesn't find the controller (in the case below - AuthController). My workaround is to just include them, which works but doesn't feel right.

I was thinking of two potential workarounds, but wanted to ask about it first. Workarounds:
- Explicitly include all my controllers
- Regenerate the application using the current head, and move the code across in the hope that newly generated apps don't have this issue

My existing routes.jl:
```
using Router

# Importing controllers manually
include("../app/resources/auth/controller.jl")

baseApi = "api/v0/"

route("/") do
  Router.serve_static_file("/welcome.html")
end

# Status operations
# Works
route(baseApi * "status", method = GET, named = :getStatus) do
  "UP!"
end
# Auth operations - don't work, can't find AuthController
route(baseApi * "auth/authenticate", AuthController.authenticate, method = POST, named = :authenticate)
route(baseApi * "auth/refreshtoken", AuthController.refreshToken, method = POST, named = :refreshToken)
```

**Comment by essenciary** [comment]
OK, I understand. 

Try this: 
1 - rename `/app/resources/auth/controller.jl` to `/app/resources/auth/AuthController.jl`
2 - replace `include("../app/resources/auth/controller.jl")` with `using AuthController`

This should be all.

**Comment by essenciary** [comment]
As a side note, an "auth" is not really a resource in the REST meaning of the word. So depending on the functionality that you have in `AuthController` it might be more natural to set up an `Auth` library (module) and place it in `/lib`. All modules in `/lib` are also automatically loaded by Genie and available in `routes.jl`. (However, if your `AuthController` needs to orchestrate interactions between auth views and an `Auth` model then you're better off with a `Controller`).

**Comment by GearsAD** [comment]
Gotcha - that pattern works - thanks!

Yes, it was a custom auth endpoint originally, but it's vestigial at the moment (just my test endpoint).

**Comment by essenciary** [comment]
Excellent! 😀
