### ISSUE TITLE
DB Initialization Removed

### ISSUE THREAD

**Issue by berzley** [essenciary/Genie.jl#35]
e5595725d6684fde3315a801b249d2e04a33d8cc  Removed `Genie.REPL.db_init()` and is still referenced in documentation. 

Best I can tell this function is still needed for initializing schema_migrations.
Alternatively a user could just run `SearchLight.create_migrations_table(App.config.db_migrations_table_name)` directly.

**Comment by essenciary** [comment]
The documentation is out of sync -- I've made a lot of changes lately. I'll get to that soon as I'm planning a revamp of the docs as well plus automatic regeneration via CI. 

That being said, the removal of `db_init` is part of a cleanup and disentangling process: the idea is to separate Genie (used for handling web requests and responses) from SearchLight (the ORM). Thus, `db_init` is now part of `SearchLight.Generator` and is invoked from Genie as `SearchLight.create_migrations_table(App.config.db_migrations_table_name)`, like you said. 

So yes, the documentation is due for an update.
