### ISSUE TITLE
Error "404 Not Found" when starting existing web app

### ISSUE THREAD

**Issue by aalexandersson** [essenciary/Genie.jl#56]
I can create a new web app and see it in the browser. But I cannot start an existing web app it seems. 

The local web server is running according to Julia:
```
shell> cd Anders_cool_new_app
F:\Julia\Anders_cool_new_app

julia> using Genie

julia> Genie.AppServer.startup()
[ Info: Listening on: Sockets.InetAddr{Sockets.IPv4}(ip"127.0.0.1", 0x1f40)
[2018-09-13 12:35:12|info]: Web server running at 127.0.0.1:8000
```

But when I go to http://localhost:8000/ I get two errors:

1. In the browser, I get error 
"404 Not Found
Oh dear, no page here! 
Sorry, we can not find /"

2. In Julia, I get the session error below:
```
julia> [ Info: Accept:  ?    0↑     0↓    0s 127.0.0.1:8000:8000 ?16
[ Info: Accept:  ?    0↑     0↓    0s 127.0.0.1:8000:8000 ?16
┌ Warning: throttling 127.0.0.1
└ @ HTTP.Servers C:\Users\aalexandersson\.julia\packages\HTTP\nUK4f\src\Servers.jl:128
┌ Info: HTTP.Messages.Request:
│ """
│ GET / HTTP/1.1
│ Host: localhost:8000
│ Connection: keep-alive
│ Cache-Control: max-age=0
│ Upgrade-Insecure-Requests: 1
│ User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
│ Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
│ Accept-Encoding: gzip, deflate, br
│ Accept-Language: en-US,en;q=0.9
│
└ """
[ Info: Accept:  ?    0↑     0↓    0s 127.0.0.1:8000:8000 ?16
[2018-09-13 12:35:35|info]: Session error
[2018-09-13 12:35:35|info]: C:\Users\aalexandersson\.julia\packages\Genie\Qst2l\src\Sessions.jl:30
[2018-09-13 12:35:36|info]: Generating temporary session id
[2018-09-13 12:35:37|info]: [2018-09-13T12:35:37.418] -- :/ -- Done
```

I am using Windows 7.

**Comment by essenciary** [comment]
A Genie app is a distinct project which uses Genie but is not part of Genie. 

You need to execute `bin/repl.bat` or `bin/server.bat` in the terminal, while in the app's dir. Or in a Julia REPL, also in the app's folder, run `include("genie.jl")` -- this will bootstrap the app. 
Check out the updated README at https://github.com/essenciary/Genie.jl#loading-an-app

P.S. -- it might be a good idea to automatically load the app if Genie is loaded in an app's dir. I'll give it a try...

**Comment by aalexandersson** [comment]
Ok, I tried but still localhost does not show output in the browser (after refresh). Maybe I did something wrong? It's very possible (but not intended)! First, here is more detailed version info:

```
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, nehalem)
Environment:
  JULIA_EDITOR = "C:\Users\aalexandersson\AppData\Local\atom\app-1.29.0\atom.exe" -a
  JULIA_NUM_THREADS = 4
```

How should I execute the bat files? If in Windows I double-click `bin/repl.bat` I get this output (no error)

![image](https://user-images.githubusercontent.com/20467610/45549924-6b4fd800-b7f7-11e8-9391-338260319e76.png)

If I instead in Windows double-click `bin/server.bat` I get this output (error could not open file):

![image](https://user-images.githubusercontent.com/20467610/45550037-c08be980-b7f7-11e8-8b42-05dfff30a244.png)

If I instead run include("genie.jl") from Julia REPL in my app directory I get this output (no error):

```shell> cd Anders_cool_new_app
F:\Julia\Anders_cool_new_app

julia> include("genie.jl")
 _____         _
|   __|___ ___|_|___
|  |  | -_|   | | -_|
|_____|___|_|_|_|___|


Starting Genie in >> DEV << mode

[ Info: Recompiling stale cache file C:\Users\aalexandersson\.julia\compiled\v1.0\Genie\8eazC.ji for Genie [c43c736e-a2d1-11e8-161f-af95117fbd1e]

genie>
```

But sometimes the [Info: ...] part is omitted. A final detail, which might not matter, is that when the new app was running I used to get lots of "listening/uptime" output.

**Comment by aalexandersson** [comment]
I fixed it, There seems to be one missing step in the instructions, because it is not obvious to a beginner like myself: You need to start the web server once Genie is up if you want to see the app in the browser.

```
genie> Genie.AppServer.startup()
[ Info: Listening on: Sockets.InetAddr{Sockets.IPv4}(ip"127.0.0.1", 0x1f40)
[2018-09-14 09:27:24|info]: Web server running at 127.0.0.1:8000
```

**Comment by essenciary** [comment]
@aalexandersson That's right - once you include "genie.jl" that load's the app's environment -- but then the server needs to be started. 

You're right, it's not clear. I'll put more details in the doc. Also, I'll see maybe Genie can automatically start the app if `using Genie` in an app's folder. Finally, the fact that bin/server.bat doesn't work looks like a bug, I'll check it out.

**Comment by essenciary** [comment]
@aalexandersson Is this better? 
https://github.com/essenciary/Genie.jl#loading-an-app

**Comment by aalexandersson** [comment]
Thank you, the wording is much clearer now. I don't know why `bin/server.bat` resulted in an error (I don't have access yet to Julia in the weekends) but I will keep testing your package. It is very promising!

**Comment by Kalokola** [comment]
if you are using vscode enter into the app's main directory type bin/server.bat press enter this will run your server. Then press the add icon to add a new terminal and type bin/repl.bat press enter and a julia  command line  specific to your project  will open. Go your favorite browser and see through your urls.
