### ISSUE TITLE
Readme enhancements

### ISSUE THREAD

**Issue by lanrebr** [essenciary/Genie.jl#57]
url:  https://github.com/essenciary/Genie.jl

**Location**: Working with resources/Adding views/Rendering views
**Missing**: explain that the html! method comes from the Renderer class\
**Example**: Add "using Genie.Renderer" at the top of the definition of the billgatesbooks function

**Location**: Generate the Controller
**Missing**: explain that the user should test the BooksController.billgatesbooks function in Julia to make sure it produces the expected text to avoid issues later
**Example**: genie> BooksController.billgatesbooks()

**Comment by essenciary** [comment]
Sounds good, thanks, will add (or feel free to make the changes yourself and make a pull request, if you're so inclined).

**Comment by essenciary** [comment]
Done, thanks!
