### ISSUE TITLE
Precompile / sysimg / binary

### ISSUE THREAD

**Issue by d4tocchini** [essenciary/Genie.jl#58]
@essenciary, have you tried (or know about) precompiling a Genie project into a single executable? Ideally for use in a desktop app, something like https://github.com/NHDaly/ApplicationBuilder.jl   

Or, what about building a sysimg?  I got my way through generating a sysimg but so far it hasnt produced any noticeable benefit -- the structure of the project seems to require a little more hoop jumping to ensure all deps are compiled AOT...  

I'm loving the perf & boilerplate you established with Genie, but that initial wait time to compile each route as they are first-requested just kills the possibilities beyond traditional long-running deployments.  Is there a flag I'm missing to precompile each Flax view/route?  

I'm pretty confident the killer feature that'll open the floodgates of adoption, with Julia web servers in general, would be parity with golang's ability to spit out a self-contained binary. Any electron app beyond the scope of throwaway utilities ends up with non-trivial server & DB systems (ie https://github.com/Foundry376/Mailspring) that would benefit herein. Any thoughts/advice in this direction?

**Comment by essenciary** [comment]
@d4tocchini Sorry, this fell through the cracks. 

Is sysimg still a thing? Somehow I thought it's no longer used in Julia 1? 

Building an executable is definitely interesting but seems like a difficult issue, I've been following a few blog posts and a talk a JuliaCon2018 - it takes a lot of tweaking and there's no working generic solution at the time. I don't think first time compilation is a problem for an app running on a server which isn't restarted for months at a time. And if it would be, an integration test which hits all the routes will solve this easier. 

I'd love to see native compilation but it's not something I'll do anytime soon.
