### ISSUE TITLE
Post request with payload:  Example

### ISSUE THREAD

**Issue by abannsunny** [essenciary/Genie.jl#60]
Hi,

I very recently started working with Genie. Really excited to try it out!

I searched for an example in the docs to handle a post request with request payload and I couldn't  find any. Could you please share an example on how to handle a post request and handle it in a controller?

Also how to start the app in production mode?

Thank you,
Abann

**Comment by essenciary** [comment]
@abannsunny 
Sure -- I'll add some info about these to the readme, I'll try to do this today. I'll update here when done.

**Comment by abannsunny** [comment]
Thank you!

**Comment by essenciary** [comment]
@abannsunny Sorry for the delay -- work got in the way :) 
Here is the promised section: https://github.com/essenciary/Genie.jl#handling-forms
I'll add an extra part about file uploads soon -- but I hope till then, this is enough to get you started.
