### ISSUE TITLE
Server closes connection unexpectedly

### ISSUE THREAD

**Issue by CarpeNecopinum** [essenciary/Genie.jl#62]
For some reason, the "Hello World"-kinda example won't work for me:
```
using Genie
import Genie.Router: route

route("/") do
    "Hi there!"
end
Genie.AppServer.startup()
```
in juno will tell me the server is running on port 8000, but any browser I point at localhost:8000 will complain that the connection was unexpectedly closed.

Similarly when trying with netcat, the connection is closed after I sent `GET / HTTP/1.1` rather than sending back the "Hi there!".

Using HTTP directly instead like
```
using HTTP
HTTP.listen() do http::HTTP.Request
    HTTP.Response("Hi there!")
end
```
creates the expected result.

**Comment by CarpeNecopinum** [comment]
OS: Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
Julia: Version 1.0.0 (2018-08-08)
Genie Version: cloned from master like half an hour ago

**Comment by essenciary** [comment]
@CarpeNecopinum Looks like a local issue, I can't reproduce
<img width="1303" alt="debian gnu linux 9 2018-10-01 16-12-36" src="https://user-images.githubusercontent.com/11292378/46293882-e6a1df80-c594-11e8-90ae-6a86ab31e1dd.png">
