### ISSUE TITLE
how about the performance 

### ISSUE THREAD

**Issue by 564064202** [essenciary/Genie.jl#63]
1. does it use libuv?
2.how about the performance vs nginx or apache?

**Comment by c42f** [comment]
1. Julia 1.0 uses `libuv` in the runtime to handle async tasks so the performance profile should currently be similar to node. However, when the parallel task runtime arrives (https://github.com/JuliaLang/julia/pull/22631) tasks will be able to run on multiple threads. The concurrent performance profile will then improve to be more similar to `go`.

2. No idea yet, I'm just starting to think about using `Genie`!

**Comment by essenciary** [comment]
2. You can't really compare Genie, which is a web framework, with Nginx or Apache, which are web servers. 

Genie does bundle HTTP.jl. So I guess if you want to compare servers, you can just ask the developers of HTTP.jl. 

However, the servers are not exclusive. For instance, my approach in production is to use Nginx as a reverse proxy and cache layer for Genie apps using HTTP.jl. 

Regarding performance in general, at this point, I'm more concerned about features, stability, and documentation. Julia should provide a good enough performance foundation - any bottlenecks can be fixed later on by refactoring the problematic functions.

**Comment by fargolo** [comment]
This is a C10k benchmark comparing Nodejs, Apache and HTTP.jl:
https://github.com/aj-monk/C10k.jl

**Comment by essenciary** [comment]
@fargolo Interesting benchmark, thanks for sharing. A few comments: 
* HTTP.jl is at 0.8.x now and I understood that performance has improved - it would be interesting to recheck
* although Julia is really good at file IO, I don't think a file server is the best use case for Julia. Ngnix is much-much-much better at serving static files than most anything else so in a real production environment that's what we'd use. Outputting a JSON string would be a more realistic and relevant test.
