### ISSUE TITLE
  Building EzXML BUG V(1.1)

### ISSUE THREAD

**Issue by 564064202** [essenciary/Genie.jl#64]
Building EzXML ────→ `~/.julia/packages/EzXML/DUxj7/deps/build.log`
┌ Error: Error building `EzXML`: 
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ [ Info: Downloading https://github.com/bicycle1885/XML2Builder/releases/download/v1.0.1/XML2Builder.v2.9.7.x86_64-linux-gnu.tar.gz to /root/.julia/packages/EzXML/DUxj7/deps/usr/downloads/XML2Builder.v2.9.7.x86_64-linux-gnu.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/bicycle1885/XML2Builder/releases/download/v1.0.1/XML2Builder.v2.9.7.x86_64-linux-gnu.tar.gz to /root/.julia/packages/EzXML/DUxj7/deps/usr/downloads/XML2Builder.v2.9.7.x86_64-linux-gnu.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] macro expansion at ./logging.jl:313 [inlined]
│  [3] #download#89(::Bool, ::Function, ::String, ::String) at /root/.julia/packages/BinaryProvider/cVlaj/src/PlatformEngines.jl:487
│  [4] #download at ./none:0 [inlined]
│  [5] #download_verify#90(::Bool, ::Bool, ::Bool, ::Function, ::String, ::String, ::String) at /root/.julia/packages/BinaryProvider/cVlaj/src/PlatformEngines.jl:567
│  [6] #download_verify at ./none:0 [inlined]
│  [7] #install#129(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at /root/.julia/packages/BinaryProvider/cVlaj/src/Prefix.jl:314
│  [8] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at ./none:0
│  [9] top-level scope at /root/.julia/packages/EzXML/DUxj7/deps/build.jl:36
│  [10] include at ./boot.jl:317 [inlined]
│  [11] include_relative(::Module, ::String) at ./loading.jl:1041
│  [12] include(::Module, ::String) at ./sysimg.jl:29
│  [13] include(::String) at ./client.jl:388
│  [14] top-level scope at none:0
│ in expression starting at /root/.julia/packages/EzXML/DUxj7/deps/build.jl:32
│ [16:52:17] 
│ [16:52:17] curl: (35) Peer reports incompatible or unsupported protocol version.
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069
  Building Gumbo ────→ `~/.julia/packages/Gumbo/G7Qbw/deps/build.log`
┌ Error: Error building `Gumbo`: 
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ ┌ Warning: Could not extract the platform key of https://github.com/JuliaWeb/GumboBuilder/releases/download/v0.1.0/Gumbo.x86_64-linux-gnu.tar.gz; continuing...
│ └ @ BinaryProvider ~/.julia/packages/BinaryProvider/cVlaj/src/Prefix.jl:185
│ [ Info: Downloading https://github.com/JuliaWeb/GumboBuilder/releases/download/v0.1.0/Gumbo.x86_64-linux-gnu.tar.gz to /root/.julia/packages/Gumbo/G7Qbw/deps/usr/downloads/Gumbo.x86_64-linux-gnu.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/JuliaWeb/GumboBuilder/releases/download/v0.1.0/Gumbo.x86_64-linux-gnu.tar.gz to /root/.julia/packages/Gumbo/G7Qbw/deps/usr/downloads/Gumbo.x86_64-linux-gnu.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] macro expansion at ./logging.jl:313 [inlined]
│  [3] #download#89(::Bool, ::Function, ::String, ::String) at /root/.julia/packages/BinaryProvider/cVlaj/src/PlatformEngines.jl:487
│  [4] #download at ./none:0 [inlined]
│  [5] #download_verify#90(::Bool, ::Bool, ::Bool, ::Function, ::String, ::String, ::String) at /root/.julia/packages/BinaryProvider/cVlaj/src/PlatformEngines.jl:567
│  [6] #download_verify at ./none:0 [inlined]
│  [7] #install#129(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at /root/.julia/packages/BinaryProvider/cVlaj/src/Prefix.jl:314
│  [8] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at ./none:0
│  [9] top-level scope at /root/.julia/packages/Gumbo/G7Qbw/deps/build.jl:27
│  [10] include at ./boot.jl:317 [inlined]
│  [11] include_relative(::Module, ::String) at ./loading.jl:1041
│  [12] include(::Module, ::String) at ./sysimg.jl:29
│  [13] include(::String) at ./client.jl:388
│  [14] top-level scope at none:0
│ in expression starting at /root/.julia/packages/Gumbo/G7Qbw/deps/build.jl:23
│ [16:52:32] 
│ [16:52:32] curl: (35) Peer reports incompatible or unsupported protocol version.

**Comment by essenciary** [comment]
When exactly did you get that? When installing Genie? Or when building a Genie app?

**Comment by essenciary** [comment]
Closing this as I can't replicate it and no more details were provided.
