### ISSUE TITLE
respond_with_html needs full path

### ISSUE THREAD

**Issue by c42f** [essenciary/Genie.jl#66]
Hi, I'm trying to follow the step by step guide at

https://geniejl.readthedocs.io/en/latest/guides/Step%20by%20step%20app%20development%20with%20Genie/

When I get to adding the line
```
    respond_with_html("home", "home_page.md")
```

The home page is broken. To get it to work, I needed to replace this line with the full path to `home_page.md`:

```
    respond_with_html("home", "app/resources/home/views/home_page.md")
```

I've followed through the logic from Genie.Renderer to Genie.Flax and I don't see any path translation going on. Should there be?

**Comment by essenciary** [comment]
That's old and needs to be updated - can you please follow the instructions in the README for now: https://github.com/essenciary/Genie.jl
