### ISSUE TITLE
Genie config seems to overuse `eval`

### ISSUE THREAD

**Issue by c42f** [essenciary/Genie.jl#67]
Just browsing through the code, I can see a lot of use of `eval`, which mostly seems to be used for pulling in configuration from the application. This seems a little fishy to me - generally `eval` should only be used in specialized circumstances, for example if you really need to generate a bunch of function definitions like you're doing inside `Flax`. For other uses, consider a setter function, for example:

```julia
module Foo

_config = nothing

function foo_config(c)
    global _config = c
end

function use_config()
    @info "using global config" config=_config
end

end
```

Thence

```julia
julia> Foo.foo_config("blah")
"blah"

julia> Foo.use_config()
┌ Info: using config
└   config = "blah"
```

Using `eval` for pulling in configuration seems problematic and unlikely to work with precompilation. Actually I'm surprised it works at all! I'm probably missing something about how Genie initializes itself.

**Comment by c42f** [comment]
Maybe a simple example would be easier to discuss:

```julia
julia> module Foo
           eval(:(const engine = 1))
       end
Main.Foo
```
At this point `engine` already exists within foo:
```julia
julia> Foo.engine
1
```

**Comment by essenciary** [comment]
Thanks for the advice - I removed a lot of these injected dependencies as they were a design smell. Now Genie and SearchLight are isolated packages and the Genie app (the project) orchestrates the communication between the two. 

Also, pre v1.0, I'm going through a simplification and speeding up phase, so I'm removing all functionality which has not proved useful enough and is not mature enough. The pluggable `HTMLTemplateEngine` idea was scrapped pending a proper pluggable architecture.
