### ISSUE TITLE
Example app extremely slow in windows

### ISSUE THREAD

**Issue by DavidBernal** [essenciary/Genie.jl#70]
I follow the example app steps, and when I load the ```/hello``` route, the request takes 4 seconds. I don't see any errors or fails

Env:
Windows 10
Julia: v1.0.0

**Comment by essenciary** [comment]
Thanks - every time? Or the first time?

**Comment by DavidBernal** [comment]
Every time.

**Comment by DavidBernal** [comment]
I tried in another computer, and takes 500ms. Better but to much anyway. I tested Mux to discard a julia problem and it seems correctly.

**Comment by essenciary** [comment]
@DavidBernal Thanks for the update - can you please share how you benchmarked so I can replicate?

**Comment by essenciary** [comment]
There doesn't seem to be any problem with Genie itself - the response time on my mac is 79ms. I'll try it now in a VM with Win 10, but that will affect the performance as the VM is considerably slower. So I'm not sure how relevant will that be, but let's see. 
<img width="846" alt="speed" src="https://user-images.githubusercontent.com/11292378/47443495-b5dc5100-d7b4-11e8-9744-90674baadaac.png">

**Comment by essenciary** [comment]
Yes, very bad on Win 10 in my VM - around 5s! :-O

**Comment by essenciary** [comment]
Ah no actually, false alarm. Turned out to be the VM was using up all the resources to perform a windows update. After the update, the response time is around 650ms. So yes, that's a few times slower compared to the mac. I'll see what the profiler has to say.

**Comment by DavidBernal** [comment]
I'm out until friday so I can't do test now. Anyway, 650ms for a text in local network is a lot.

**Comment by essenciary** [comment]
Yes, something's off on Windows. HTTP.jl responds fast, so it's something else in the stack which is fast on Mac but slow on Win.

**Comment by essenciary** [comment]
@DavidBernal Closing this as the performance has improved massively due to latest tweaks, 16ms now: 
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/11292378/53374707-6328c680-3959-11e9-96ea-795427d2d8f7.png">

**Comment by DavidBernal** [comment]
Nice, I will try again.
