### ISSUE TITLE
Genie.Cookies.set! has 2 kinds of return type

### ISSUE THREAD

**Issue by p1scescom** [essenciary/Genie.jl#73]
`Genie.Cookies.set!` has 2 kinds of return type ; Vector{HTTP.Cookies.Cookie},Dict{String,HttpCommon.Cookie}.
A set! function calls other set! function.
But their return type can't convert each other. 
So it needs fix.
Which return type is that you want type ?

https://github.com/essenciary/Genie.jl/blob/d088f4676d3cc5db17c26d31f69796384f389b94/src/Cookies.jl#L50
https://github.com/essenciary/Genie.jl/blob/d088f4676d3cc5db17c26d31f69796384f389b94/src/Cookies.jl#L59

**Comment by essenciary** [comment]
Hmmm... seems something was lost in translation from `HttpServer` to `HTTP`. 

Looks like we could do with only one function: 
```julia
function set!(res::HTTP.Response, key::Union{String,Symbol}, value::Any, attributes::Dict = Dict()) :: Vector{HTTP.Cookies.Cookie}
  normalized_attrs = Dict{Symbol,Any}()
  for (k,v) in attributes
    normalized_attrs[Symbol(lowercase(string(k)))] = v
  end
  HTTP.Cookie(string(key), string(value) |> Genie.Encryption.encrypt; normalized_attrs...)

  HTTP.Cookies.readsetcookies("", "")
end
```

**Comment by p1scescom** [comment]
Yes, set! can't set cookies. So now, I write
```
push!(response(@params).headers,
              "Set-Cookie" => dict2cookies([("account", account)]) * "\r\nSet-Cookie: " * dict2cookies([("uniquekey", uniquekey)]))
```
when get , I don't use my original get
```
function noencryptget(req, key::Union{String,Symbol}) :: Nullable{String}
  if haskey(Dict(req.headers), "Cookie")
    cookies = Cookies.to_dict(req)
    if haskey(cookies, string(key))
      return Nullable{String}(cookies[string(key)])
    end
  end
  Nullable{String}()
end

```
Maybe this problem isn't Genie's, cannot some `Set-Cookie` s.
I use a mad method.
