### ISSUE TITLE
Please tag release

### ISSUE THREAD

**Issue by GearsAD** [essenciary/Genie.jl#77]
Hi Essenciary,

Could you please tag releases between significant changes? It would make it easier for users to stage the upgrade of their packages that make use of Genie. 

Great package by the way, thanks for writing.

**Comment by jingpengw** [comment]
+1
BTW, this is a duplicate of another issue: https://github.com/essenciary/Genie.jl/issues/26

**Comment by essenciary** [comment]
Sure! I felt that it was not stable enough in the past - but I think by now it would make sense, given the enhanced version management in Julia v1.

**Comment by dehann** [comment]
+1

**Comment by essenciary** [comment]
Working on it :)

**Comment by GearsAD** [comment]
Just saw that it was tagged - thanks!
