### ISSUE TITLE
can not open the discover packages website 

### ISSUE THREAD

**Issue by jingpengw** [essenciary/Genie.jl#78]
http://genieframework.com/packages

this is what I get:

```
502 Bad Gateway
nginx/1.10.3 (Ubuntu)
```

**Comment by essenciary** [comment]
Thanks - the website is a bit outdated. And the packages app needs a bit more work for now, to support Julia 1.

**Comment by essenciary** [comment]
Removed the packages website as I don't plan on fixing it anytime soon. I recommend https://juliaobserver.com instead.
