### ISSUE TITLE
[MethodError(convert, (String, nothing)] has occurred.(bgbooks new.jl.html)

### ISSUE THREAD

**Issue by yshutaro** [essenciary/Genie.jl#80]
Dear developers,

https://github.com/essenciary/Genie.jl
I tried to make an example while looking at it. 

`app / resources / books / views / new.jl.html`
We created up to and accessed the following.
http://localhost:8000/bgbooks/new
Then, `500 Internal Server Error`  occurred.

The following is output in the log.

```
[2018-11-05 17:09:23|info]: Including app/resources/books/views/new
[2018-11-05 17:09:25|warn]: MethodError(Genie.Renderer.Flax.normal_element, (["Bill Gates' website"], "a", Pair{Symbol,Any}(:href, "https://www.gatesnotes.com/Books"), Pair{Symbol,Any}(:target, "_blank")), 0x0000000000006226) at /Users/<myname>/.julia/packages/Genie/4Uuoi/src/Flax.jl:219
[2018-11-05 17:09:25|info]: MethodError(convert, (String, nothing), 0x000000000000621f)
[2018-11-05 17:09:25|info]: /Users/<myname>/.julia/packages/Genie/4Uuoi/src/Flax.jl:259
[2018-11-05 17:09:25|info]: Failed invoking controller
[2018-11-05 17:09:25|info]: MethodError(convert, (String, nothing), 0x000000000000621f)
[2018-11-05 17:09:26|info]: /Users/<myname>/.julia/packages/Genie/4Uuoi/src/Router.jl:466
[2018-11-05 17:09:27|warn]: Distributed.RemoteException(1, CapturedException(MethodError(convert, (String, nothing), 0x000000000000621f), Any[(macro expansion at util.jl:157 [inlined], 1), (#_include_template#4(::Bool, ::String, ::Function, ::String) at Flax.jl:211, 1), (#_include_template at none:0 [inlined], 1), (macro expansion at util.jl:156 [inlined], 1), (#include_template#3(::Bool, ::String, ::Function, ::String) at Flax.jl:162, 1), (include_template at Flax.jl:160 [inlined], 1),
(snip)
```

The environment is as follows.
```
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)

julia> Pkg.installed()
Dict{String,Union{Nothing, VersionNumber}} with 7 entries:
  "Juno"        => v"0.5.3"
  "Genie"       => v"0.1.0"
  "IJulia"      => v"1.13.0"
  "Plots"       => v"0.21.0"
  "Flax"        => v"0.0.0"
  "Atom"        => v"0.7.9"
  "SearchLight" => v"0.1.0"
```

**Comment by essenciary** [comment]
Can you 
`pkg> rm Flax` 
I'm not sure why it's there... 

Also, please check that `new.jl.html` looks like the one in the sample app here: 
https://github.com/essenciary/Genie-Searchlight-example-app

**Comment by yshutaro** [comment]
@essenciary 
Thank you for the quick reply.

> I'm not sure why it's there...

I was installing Flax at first looking at "Quick start" on the following page.
https://geniejl.readthedocs.io/en/latest/build/

I will reproduce the environment and see the sample and try again.

**Comment by essenciary** [comment]
@yshutaro Ah sorry, that's old, I'll try to update that ASAP. Please use the README: 
https://github.com/essenciary/Genie.jl

**Comment by yshutaro** [comment]
@essenciary 
Thank you for your response.

I  have re-created the new environment, but the same error occurred.
I will check it a bit more.
About Julia language I am a beginner and still studying, so reading source is also a study.
Genie is similar to Laravel and easy to use! Thank you for making!

**Comment by yshutaro** [comment]
Although I do not understand the cause, when I erased the "<a>" tag and "<form>" tag, the error ceased to appear. (Although it can not be used as an application)

```
<h2>Add a new book recommended by Bill Gates</h2>
<p>
</p>
  <input type="text" name="book_title" placeholder="Book title" /><br />
  <input type="text" name="book_author" placeholder="Book author" /><br />
  <input type="submit" value="Add book" />
```

**Comment by yshutaro** [comment]
@essenciary 
I am sorry that my explanation was bad.

I redoed the following contents in order from the beginning. However, the same error occurs in the same place. It is the place of new.jl.html.
https://github.com/essenciary/Genie.jl
I tried it in two environments, but the same error occurred. I will report it if I can identify a more detailed error.

**Comment by essenciary** [comment]
1. Have you removed Flax? That's part of Genie now so the version you have installed separately is old. 
2. Is `new.jl.html` like this: https://github.com/essenciary/Genie-Searchlight-example-app/blob/master/app/resources/books/views/new.jl.html

**Comment by yshutaro** [comment]
1. Yes

Yes. It has been deleted.
The package currently installed is below.

```
julia> Pkg.installed()
Dict{String,Union{Nothing, VersionNumber}} with 6 entries:
  "Juno"        => v"0.5.3"
  "Genie"       => v"0.1.0"
  "IJulia"      => v"1.13.0"
  "Plots"       => v"0.21.0"
  "SearchLight" => v"0.1.0"
  "Atom"        => v"0.7.9"
```

2. Yes

What I created is below.

```
<h2>Add a new book recommended by Bill Gates</h2>
<p>
  For inspiration you can visit <a href="https://www.gatesnotes.com/Books" target="_blank">Bill Gates' website</a>
</p>
<form action="$(Genie.Router.link_to(:create_book))" method="POST">
  <input type="text" name="book_title" placeholder="Book title" /><br />
  <input type="text" name="book_author" placeholder="Book author" /><br />
  <input type="submit" value="Add book" />
</form>
```

**Comment by essenciary** [comment]
Can you make a zip with the app, I'll check it out on my mac.

**Comment by yshutaro** [comment]
(When I received a reply from you,  in Japan, it was midnight so I fell asleep.)
This time, we attached the second environment（My workplace Windows "Bash on windows"）
Since my home environment is a Mac, I think that I will send a file on Mac when I get home.

[your_cool_new_app.zip](https://github.com/essenciary/Genie.jl/files/2555855/your_cool_new_app.zip)

**Comment by essenciary** [comment]
@yshutaro It looks like you didn't do this part of the tutorial: 

"Genie comes with a special file called an initializer, which can automatically load the database configuration and setup SearchLight. Just edit "config/initializers/searchlight.jl" and uncomment the code."

Without it Genie doesn't know how to use SearchLight.

I will update the README, maybe it's not very clear that this part is important. Sounds a bit like it's optional, which is not the case for successfully following through the tutorial.

**Comment by yshutaro** [comment]
@essenciary 
Thank you for your detailed answer.
It certainly skipped over the part pointed out.
Fixing `config/initializers/searchlight.jl` resulted in no error and it is displayed!

Thank you very much!!!

I close this issue.
