### ISSUE TITLE
Problem with the interactive mode.

### ISSUE THREAD

**Issue by SyntheticMind** [essenciary/Genie.jl#81]
I read a lot of file. But so far, i can't find anything about the key shortcut. And specially: When you are not in the Julia mode (Julia>) how do you return to it?

**Comment by essenciary** [comment]
It's not an actual mode yet, just a cursor change to indicate you're in a genie app environment. You don't need to exit it, it is the Julia prompt.

**Comment by SyntheticMind** [comment]
Let say that i had switch the Pkg mode. How i can to return in Julia mode ?

**Comment by essenciary** [comment]
Pkg mode is not part of Genie, is part of Julia itself. Just press backspace on an empty line in the REPL while in Pkg mode and you'll get back to Julia mode.
