### ISSUE TITLE
SearchLight not defined

### ISSUE THREAD

**Issue by dimitraVrs** [essenciary/Genie.jl#83]
I am getting the following message :   ERROR: UndefVarError: SearchLight not defined, when i run 
SearchLight.Configuration.load_db_connection().
I followed the instructions mentioned here https://github.com/essenciary/Genie.jl#setup-the-database-connection to add SearchLight and i am using version 1.0.2 of Julia (also i added Genie according to steps of the page i mentioned).
Any suggestions?
Thank you in advance.

**Comment by essenciary** [comment]
@dimitraVrs Hmmm... rereading the tutorial it seems like I forgot to add the `julia> using SearchLight` part, to bring the SearchLight package into scope. Can you try running it?

**Comment by dimitraVrs** [comment]
I tried it, but i get a "SearchLight not found in current path" error..

**Comment by essenciary** [comment]
Sounds like SearchLight was not installed. 
Can you show me the output of: `julia> versioninfo()` and `pkg> st` please.

**Comment by dimitraVrs** [comment]
The output is:
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)

(v1.0) pkg> st
    Status `~/.julia/environments/v1.0/Project.toml`
  [c43c736e] Genie v0.1.0 #master (https://github.com/essenciary/Genie.jl)

**Comment by essenciary** [comment]
OK - so as you can see in `pkg> st` there is no SearchLight installed. Also, it's not running in the project's pkg environment. 

Seems like you need to go back to this section of the README: 

> Let's begin by adding SearchLight to our Genie app. All Genie apps manage their dependencies in their own environment, through their Project.toml and Manifest.toml files. So you need to make sure that you're in pkg> shell mode first and that our books project is loaded. You do this by running pkg> activate . in the root folder of the app. Next, we add SearchLight:
> pkg> add https://github.com/essenciary/SearchLight.jl

**Comment by dimitraVrs** [comment]
I 've done this before, but there are still errors. One of them is "ERROR: LoadError: CodecZlib.jl is not installed properly"...

**Comment by essenciary** [comment]
Can you paste the full error? Looks like some dependency of some package needed by SearchLight fails on your OS.

**Comment by dimitraVrs** [comment]
I got this after julia> using SearchLight command. The errors are " ERROR: LoadError: CodecZlib.jl is not installed properly, run Pkg.build("CodecZlib") and restart Julia.",
"ERROR: LoadError: LoadError: Failed to precompile CodecZlib [944b1d66-785c-5afd-91f1-9de20f533193] to /home/dimitra/.julia/compiled/v1.0/CodecZlib/1TI30.ji.",
"ERROR: LoadError: Failed to precompile DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0] to /home/dimitra/.julia/compiled/v1.0/DataFrames/AR9oZ.ji.",
"ERROR: Failed to precompile SearchLight [340e8cb6-72eb-11e8-37ce-c97ebeb32050] to /home/dimitra/.julia/compiled/v1.0/SearchLight/GqMHX.ji.".

**Comment by dimitraVrs** [comment]
Also, recommendations following errors, don't make things better..

**Comment by dimitraVrs** [comment]
I tested if things work on ubuntu 16.04.5 (the other operating system is ubuntu 18.04).. This time using SearchLight doesn't give an error, but SearchLight.Configuration.load_db_connection() gives the following error: "ERROR: While scanning a simple key at line 5, column 2: could not find expected ':' at line 6, column  2".

**Comment by essenciary** [comment]
OK, so the first looks like a problem in the CodecZlib.jl package. 

As for the latest, it sounds like the install was successful - might be a parsing error when loading the DB config. 

Does your file look like this one? 
https://github.com/essenciary/Genie-Searchlight-example-app/blob/master/config/database.yml

**Comment by dimitraVrs** [comment]
You are right, i didn't gave value to env variable.
But, once again i have the problems i had before...
I have no idea what went wrong and what to do....

**Comment by dimitraVrs** [comment]
EDIT:
I tried to install SearchLight again, the installation was successful and fortunatelly the database was created. 
Is there any chance that I have to install SearchLight everytime I need to use it?

**Comment by essenciary** [comment]
Happy to hear it. 
No, there's no chance for that, it's not how package installation works in Julia.
