### ISSUE TITLE
Error "404 Not Found"

### ISSUE THREAD

**Issue by dimitraVrs** [essenciary/Genie.jl#87]
I followed next steps and got an error. 
The steps are:
I created a page with a form (I followed the instructions in https://github.com/essenciary/Genie.jl/blob/master/README.md#handling-forms), then i loaded my app, started the server and visited http://localhost:8000/bgbooks/new . 
But i got error "404 Not Found"  at that point.
It would be really helpfull if you gave me suggestions about fixing the error.

**Comment by dimitraVrs** [comment]
genie> Dict{Symbol,Genie.Router.Route} with 1 entry:
  :get => Route("GET", "/", ##3#4(), Dict{Symbol,Any}(), Function[], Function[])

That's what i got after Router.named_routes().. Are routes properly defined?

**Comment by essenciary** [comment]
No, they don't look good. There's no routing between "bgbooks/new" and a handler function. Have you added these to `config/routes.jl`? 
```julia
# routes.jl
route("/bgbooks/new", BooksController.new)
route("/bgbooks/create", BooksController.create, method = POST, named = :create_book)
```

And the output of `Router.named_routes` should include them: 
```julia
:get_bgbooks        => Route("GET", "/bgbooks", billgatesbooks, Dict{Symbol,Any}(), Function[], Function[])
:get_bgbooks_new    => Route("GET", "/bgbooks/new", new, Dict{Symbol,Any}(), Function[], Function[])
:get                => Route("GET", "/", (), Dict{Symbol,Any}(), Function[], Function[])
```

**Comment by dimitraVrs** [comment]
Ok, routes are now properly defined. Still, i cannot see the page, it takes a long time to load..

**Comment by essenciary** [comment]
Yeee, you're welcome!

**Comment by scheung38** [comment]
I have a similar issue, in config/routes.jl:

```
using Genie.Router

route("/") do
  serve_static_file("/welcome.html")
end

# added
function hello_world()
  "Hello World"
end

route("/hello", hello_world)
```

but even with 

```
genie> Router.named_routes():

genie> Router.named_routes()
genie> Dict{Symbol,Genie.Router.Route} with 2 entries:
  :get_hello => Route("GET", "/hello", hello_world, Dict{Symbol,Any}(), Function[], Function[])
  :get       => Route("GET", "/", ##3#4(), Dict{Symbol,Any}(), Function[], Function[])
```

page 404 Not Found when 

http://localhost:8000/hello
