### ISSUE TITLE
Unable to run inside Docker

### ISSUE THREAD

**Issue by Seanny123** [essenciary/Genie.jl#89]
I was trying to deploy a REST service via a Docker container on AWS. I was trying to use Genie for this purpose, but I couldn't get it working on my machine, despite using identical instructions for a Flask server. See the Dockerfile and instructions in [this folder](https://github.com/Seanny123/dockerfiles/tree/master/julia-genie).

To be clear, this is no longer a priority for me, given my co-worker has figured out how to deploy our service via AWS Lambda, but I thought it was still worth mentioning. Especially since I'm having [similar issues with Bukdu](https://github.com/wookay/Bukdu.jl/issues/53), so it might be something to do with HTTP.jl?

**Comment by essenciary** [comment]
@Seanny123 Thanks for reporting this - I'll take a look, I'm curious myself.

**Comment by Seanny123** [comment]
Due to a series of embarrassing misunderstandings, I thought `0.0.0.0` and `127.0.0.1` were equivalent. They are not. By changing the code to `Genie.AppServer.startup(8080, "0.0.0.0")` the problem was resolved.

**Comment by essenciary** [comment]
Yeeee! Thanks for letting me know!
