### ISSUE TITLE
Dependence on PostgreSQL

### ISSUE THREAD

**Issue by EricForgy** [essenciary/Genie.jl#9]
PostgreSQL is not in METADATA and from the README seems like it never will be unless someone else takes the reigns. But I notice it is a dependency to run

~~~julia
julia> include(Pkg.dir("Genie","genie.jl"))
~~~

I need to run

~~~julia
julia> using PostgreSQL
~~~

before genie.jl in v0.5 will run. 

Not too serious, but just FYI :+1:

**Comment by essenciary** [comment]
In order to start a Genie interactive session through the Julia REPL, just type:
`
$> julia -L genie.jl --color=yes -q
`

Then 
```julia
using Genie, Model
```
