### ISSUE TITLE
Throttling and discarding connections

### ISSUE THREAD

**Issue by jcoleman-techempower** [essenciary/Genie.jl#91]
Out of the box, loading the default `index.html` page causes a single client connection to throttle and even discard itself. It would be nice to be able to change the rate-limiting, perhaps via the config.

**Comment by essenciary** [comment]
Good point - that's a setting in `HTTP`, I'll look into it.

**Comment by essenciary** [comment]
Updated to HTTP v0.8 which provides better performance and also allows setting the rate limits. Genie's AppServer can now be started by passing the extra params: 
```
function startup(port::Int = 8000, host::String = "127.0.0.1";
                  ws_port::Int = port + 1, async::Bool = ! Genie.config.run_as_server,
                  verbose::Bool = false, ratelimit::Rational{Int} = 1_000//1)
```
